name: Publish

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: https://registry.npmjs.org/
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install rust toolchain
      run: rustup toolchain install 1.45.0
    - name: Set default rust toolchain
      run: rustup default 1.45.0
    - name: Install NPM dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    - name: Publish to crates.io
      run: cargo publish --token "$CARGO_AUTH_TOKEN"
      env:
        CARGO_AUTH_TOKEN: ${{ secrets.CRATES_IO_PUBLISH_TOKEN }}
